### ISSUE TITLE
Sorting by exercise order fails to work in combination with filtering tags

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#80] opened 2023-09-09 10:58 UTC
The new Jutut UI provides two useful sorting options: _exercise order_ and _reverse exercise order_, which are new (I think). However, based on what I’ve observed so far, these options don’t work in combination with feedback tags or student tags.

That is, if I don’t do any tag-based filtering, the new sorting options work. But if I filter by any tag, the ordering breaks down; it looks to me like Jutut then does _oldest first_ instead of the requested _(reverse) exercise order_.

In practice, this makes the new sorting options much less useful than they might have been otherwise.

**Comment by ihalaij1** [comment] 2023-09-14 07:54
@jsorva I was unable to reproduce this bug in my local development environment. Can you check again if the problem is still happening (maybe populating the new data fields in the server fixed it)?

If the problem still persists, can you tell me exactly what you were trying to filter? Did you have a student selected and how many tags were you filtering (student tags or feedback tags)?

**Comment by Mankro** [comment] 2023-09-14 12:01
This issue is similar to #75. The new database attribute `exercise.consecutive_order` has been empty on previously existing courses since the v2.6 update.

**Comment by Mankro** [comment] 2023-09-14 12:37
The problem has been fixed in the jutut.cs server. The script for updating the database attributes was updated in the commit
https://github.com/apluslms/mooc-jutut/commit/407a2434f02d5db196e2251c5d966744f1476298

**Closed by Mankro** 2023-09-14 12:37 UTC
Labels: bug, effort: hours
